### ISSUE TITLE
Error in AvroData.java while creating Source Connector

### ISSUE THREAD

**Issue by coolnikjain** [llofberg/kafka-connect-rest#27]
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/apache/avro/Schema.<clinit>()V @39: invokevirtual
  Reason:
    Type 'com/fasterxml/jackson/databind/ObjectMapper' (current frame, stack[1]) is not assignable to 'com/fasterxml/jackson/core/ObjectCodec'
  Current Frame:
    bci: @39
    flags: { }
    locals: { }
    stack: { 'com/fasterxml/jackson/core/JsonFactory', 'com/fasterxml/jackson/databind/ObjectMapper' }
  Bytecode:
    0x0000000: bb01 1a59 b701 1bb3 004f bb01 1c59 b200
    0x0000010: 4fb7 011d b300 edb2 004f b201 1eb6 011f
    0x0000020: 57b2 004f b200 edb6 0120 57bb 0121 5910
    0x0000030: 0abd 00c8 5903 12a6 5359 0412 b353 5905
    0x0000040: 12d4 5359 0612 a753 5907 12a4 5359 0812
    0x0000050: d953 5910 0612 ce53 5910 0712 d753 5910
    0x0000060: 0812 5c53 5910 0912 e753 b801 22b7 0123
    0x0000070: b300 0cbb 0121 59b2 000c b701 23b3 000b
    0x0000080: b200 0b12 bfb9 00ec 0200 57bb 0121 59b7
    0x0000090: 0124 b300 09b2 0009 1006 bd00 c859 0312
    0x00000a0: bf53 5904 12a6 5359 0512 a753 5906 12bb
    0x00000b0: 5359 0712 5c53 5908 12e7 53b8 0125 57ba
    0x00000c0: 0126 0000 b801 27b3 0005 ba01 2800 00b8
    0x00000d0: 0127 b300 04bb 00f7 59b7 0118 b300 abb2
    0x00000e0: 00ab 1301 29b2 012a b901 0103 0057 b200
    0x00000f0: ab13 012b b201 2cb9 0101 0300 57b2 00ab
    0x0000100: 1301 2db2 012e b901 0103 0057 b200 ab13
    0x0000110: 012f b201 30b9 0101 0300 57b2 00ab 1301
    0x0000120: 31b2 00c0 b901 0103 0057 b200 ab13 0132
    0x0000130: b200 c1b9 0101 0300 57b2 00ab 1301 33b2
    0x0000140: 0134 b901 0103 0057 b200 ab13 0135 b200
    0x0000150: 67b9 0101 0300 57ba 0136 0000 b801 27b3
    0x0000160: 0003 ba01 3700 00b8 0127 b300 02b1     

	at io.confluent.connect.avro.AvroData.<clinit>(AvroData.java:155)
	at org.apache.kafka.connect.transforms.FromJson.<init>(FromJson.java:33)
	at org.apache.kafka.connect.transforms.FromJson$Value.<init>(FromJson.java:90)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.kafka.connect.runtime.ConnectorConfig.getConfigDefFromTransformation(ConnectorConfig.java:321)
	at org.apache.kafka.connect.runtime.ConnectorConfig.enrich(ConnectorConfig.java:296)
	at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:263)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$6.call(DistributedHerder.java:538)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$6.call(DistributedHerder.java:535)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:271)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:220)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
[2020-01-23 04:04:45,549] INFO 172.18.0.1 - - [23/Jan/2020:04:04:45 +0000] "POST /connectors HTTP/1.1" 500 0  275 (org.apache.kafka.connect.runtime.rest.RestServer)
[2020-01-23 04:04:57,543] INFO 172.18.0.1 - - [23/Jan/2020:04:04:57 +0000] "GET /connectors HTTP/1.1" 200 21  8 (org.apache.kafka.connect.runtime.rest.RestServer)
[2020-01-23 04:04:58,667] INFO 172.18.0.1 - - [23/Jan/2020:04:04:58 +0000] "GET /connectors HTTP/1.1" 200 21  5 (org.apache.kafka.connect.runtime.rest.RestServer)
[2020-01-23 04:04:59,657] INFO 172.18.0.1 - - [23/Jan/2020:04:04:59 +0000] "GET /connectors HTTP/1.1" 200 21  11 (org.apache.kafka.connect.runtime.rest.RestServer)
[2020-01-23 04:05:01,136] INFO 172.18.0.1 - - [23/Jan/2020:04:05:01 +0000] "GET /connectors HTTP/1.1" 200 21  6 (org.apache.kafka.connect.runtime.rest.RestServer)
[2020-01-23 04:05:06,306] INFO 172.18.0.1 - - [23/Jan/2020:04:05:06 +0000] "GET /connectors HTTP/1.1" 200 21  7 (org.apache.kafka.connect.runtime.rest.RestServer)
[2020-01-23 04:06:17,975] INFO Cluster ID: 1huMfB1eTuW8-VRZBsVrMg (org.apache.kafka.clients.Metadata)
[2020-01-23 04:07:14,191] INFO 172.18.0.1 - - [23/Jan/2020:04:07:14 +0000] "HEAD / HTTP/1.1" 200 0  6 (org.apache.kafka.connect.runtime.rest.RestServer)
[2020-01-23 04:07:14,331] INFO 172.18.0.1 - - [23/Jan/2020:04:07:14 +0000] "HEAD / HTTP/1.1" 200 0  4 (org.apache.kafka.connect.runtime.rest.RestServer)
[2020-01-23 04:07:41,339] INFO 172.18.0.1 - - [23/Jan/2020:04:07:41 +0000] "HEAD / HTTP/1.1" 200 0  3 (org.apache.kafka.connect.runtime.rest.RestServer)
[2020-01-23 04:08:16,762] INFO 172.18.0.1 - - [23/Jan/2020:04:08:16 +0000] "GET /connectors HTTP/1.1" 200 21  9 (org.apache.kafka.connect.runtime.rest.RestServer)
[2020-01-23 04:08:17,518] INFO 172.18.0.1 - - [23/Jan/2020:04:08:17 +0000] "GET /connectors HTTP/1.1" 200 21  7 (org.apache.kafka.connect.runtime.rest.RestServer)
[2020-01-23 04:09:17,855] INFO 172.18.0.1 - - [23/Jan/2020:04:09:17 +0000] "POST /connectors HTTP/1.1" 409 73  85 (org.apache.kafka.connect.runtime.rest.RestServer)
[2020-01-23 04:09:32,873] WARN /connectors (org.eclipse.jetty.server.HttpChannel)
javax.servlet.ServletException: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: Could not initialize class io.confluent.connect.avro.AvroData
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: Could not initialize class io.confluent.connect.avro.AvroData
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:432)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)

**Comment by coolnikjain** [comment]
Running on Windows 10
JJDK 1.8

**Comment by meticulo3366** [comment]
same issue, please address this

**Comment by meticulo3366** [comment]
@llofberg
